/**
 * 统一错误码 taxonomy。
 * 后端抛 AppError 时引用，前端据此做分支提示。
 * 字符串码稳定、可被前端 i18n 映射，HTTP 状态码仅作传输层语义。
 */
export const ERROR_CODES = {
  // 通用
  INTERNAL: 'INTERNAL',
  VALIDATION: 'VALIDATION',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',

  // 鉴权 / 授权
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  INVALID_CAPTCHA: 'INVALID_CAPTCHA',

  // 资源域
  COLLECTION_NOT_FOUND: 'COLLECTION_NOT_FOUND',
  DOCUMENT_NOT_FOUND: 'DOCUMENT_NOT_FOUND',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',

  // ingestion
  UNSUPPORTED_FILE_TYPE: 'UNSUPPORTED_FILE_TYPE',
  PARSE_FAILED: 'PARSE_FAILED',

  // llm（二期起常用）
  LLM_PROVIDER_ERROR: 'LLM_PROVIDER_ERROR',
  LLM_VALIDATION_FAILED: 'LLM_VALIDATION_FAILED',
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]

/** 错误码 → 默认 HTTP 状态码映射（中间件兜底用） */
export const ERROR_HTTP_STATUS: Record<ErrorCode, number> = {
  INTERNAL: 500,
  VALIDATION: 400,
  NOT_FOUND: 404,
  CONFLICT: 409,
  RATE_LIMITED: 429,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  INVALID_CREDENTIALS: 401,
  TOKEN_EXPIRED: 401,
  EMAIL_TAKEN: 409,
  INVALID_CAPTCHA: 400,
  COLLECTION_NOT_FOUND: 404,
  DOCUMENT_NOT_FOUND: 404,
  FILE_NOT_FOUND: 404,
  UNSUPPORTED_FILE_TYPE: 415,
  PARSE_FAILED: 422,
  LLM_PROVIDER_ERROR: 502,
  LLM_VALIDATION_FAILED: 422,
}
